name: Java CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code from GitHub
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Build project using Maven
    - name: Build with Maven
      run: mvn clean package

    # 4. Run Checkstyle (ensure checkstyle plugin is in pom.xml)
    - name: Run Checkstyle
      run: mvn checkstyle:check

    # 5. Build Docker image from Dockerfile
    - name: Build Docker Image
      run: docker build -t hello-world-java .

    # 6. Create artifacts folder for Docker image
    - name: Create output directory
      run: mkdir -p artifacts/docker

    # 7. Save Docker image as .tar to artifacts folder
    - name: Save Docker image as .tar
      run: docker save hello-world-java > artifacts/docker/hello-world-java.tar

