name: Java CI with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v3

    # Set up Java 17
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Build the application
    - name: Build with Maven
      run: mvn clean package

    # Lint the code using Checkstyle
    - name: Run Checkstyle
      run: mvn checkstyle:check

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t hello-world-java .

    # Save the Docker image as a .tar file
    - name: Save Docker image
      run: |
        mkdir -p artifacts/docker
        docker save hello-world-java > artifacts/docker/hello-world-java.tar

    # Upload the .tar file as an artifact
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: artifacts/docker/hello-world-java.tar

